### ISSUE TITLE
Guides

### ISSUE THREAD

**Issue by tbranyen** [nodegit/nodegit.github.com#11]
I'll start working on the styles and a default template for this.  I want to render guides via checked in markdown files.  We'll use AJAX to fetch them in and render on the client.

What would be useful are a list of introductory guides new users would like to see upon first using NodeGit.

My list:

- [ ] Installing NodeGit.
- [ ] Creating and opening a repository.
- [ ] Differences between libgit2, C++, and exposed JS properties/methods.
- [ ] Working with NodeGit Promises.

Please add comments with your ideal guides.

**Comment by orderedlist** [comment]
I'm not sure AJAXing in the content is the best call. Perhaps we can have a post-commit hook that pulls the markdown files and commits to this repository? Might be best to make this a Jekyll site if something like that were to happen.

**Comment by tbranyen** [comment]
@orderedlist I've never set up a Jekyll site or a post-commit hook in GitHub, if you'd be willing to lend a hand I'll work on a rough draft markdown file for installing NodeGit.  Ideally we can turn all the docs into a static Jekyll site.

**Comment by johnhaley81** [comment]
I would also want to have guides for all of the examples that we currently have.

Additionally we should also show all of the different ways you can authenticate. That seems to come up a lot.

**Comment by mcollina** [comment]
I think we should build a workshopper in nodeschool fashion :).

**Comment by maxkorp** [comment]
I'm inclined to agree regarding Jekyll. I also really dig the workshopper idea.

**Comment by orderedlist** [comment]
I kind of love [this line of documentation](https://github.com/libgit2/libgit2sharp/wiki/LibGit2Sharp-Hitchhiker's-Guide-to-Git) used by libgit2sharp. Basically, list a bunch of git commands you'd typically use on the command line, then show example code to replicate that using the library. Makes it easily relatable for new developers.

**Comment by johnhaley81** [comment]
I love this

**Comment by johnhaley81** [comment]
You know, I'm thinking that the convenience methods should probably aim to mirror the CLI. That would make the most sense for people trying to do normal stuff with nodegit. People that need to do more complicated stuff can then dig down through the guides but really the average user is going to want some sort of 1:1 functionality of the CLI.

**Comment by maxkorp** [comment]
I'm all for adding convenience methods to mirror CLI, but I'd be wary of ignoring focusing on convenience methods for people who aren't (If thats what you're saying). Otherwise I'd fear we end up in a situation where mirroring the CLI is easy, and the code gets rapidly more complicated as the task gets slightly more complicated.

**Comment by tbranyen** [comment]
Added in new site.
